version: "3"

volumes:
  
  mysql:

  code:
    driver: local
    driver_opts:
      type: cifs
      device: '//10.0.75.1/C/projects/myproject'
      o: 'rw,relatime,vers=2.0,sec=ntlmsspi,cache=strict,username=${USERNAME},password=${PASSWORD},domain=***,uid=0,noforceuid,gid=0,noforcegid,addr=10.0.75.1,file_mode=0755,dir_mode=0777,iocharset=utf8,nounix,mapposix,nobrl,noperm,rsize=1048576,wsize=1048576,echo_interval=60,actimeo=1'


services:

  nginx:
    image: nginx:latest
    volumes:
    - code:/www
    networks:
      projects-network:
        aliases:
          -${PROJECT}_nginx

  php-fpm:
    build: ./php-fpm/
    volumes:
    - code:/www

  mysql:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql:/var/lib/mysql
    environment:
    - MYSQL_ROOT_PASSWORD=root

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
    - PMA_HOST=${PROJECT}_mysql

  redis:
    image: redis:latest

networks:
  exetrnal:
    projects-network:
    